# Generated by Django 4.1.1 on 2022-09-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('contact_num', models.IntegerField()),
                ('age_group', models.IntegerField()),
                ('systolic_bp', models.IntegerField()),
                ('diastolic_bp', models.IntegerField()),
                ('blood_sugar', models.IntegerField()),
                ('body_temp', models.IntegerField()),
            ],
            options={
                'db_table': 'MaternalHealth',
            },
        ),
    ]
