# Generated by Django 4.1.1 on 2022-09-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternal_app', '0002_postnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprediction',
            name='heart_rate',
            field=models.IntegerField(default=100),
        ),
    ]
