# Generated by Django 4.1.1 on 2022-09-19 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternal_app', '0004_alter_healthprediction_heart_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprediction',
            name='age_group',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='healthprediction',
            name='blood_sugar',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='healthprediction',
            name='body_temp',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='healthprediction',
            name='diastolic_bp',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='healthprediction',
            name='heart_rate',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='healthprediction',
            name='systolic_bp',
            field=models.PositiveIntegerField(default=False),
        ),
    ]
