# Generated by Django 4.1.1 on 2022-09-19 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternal_app', '0005_alter_healthprediction_age_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprediction',
            name='age_group',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)]),
        ),
    ]
